apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: monitoring
spec:
  hard:
    requests.cpu: 7000m
    requests.memory: 10000Mi
    limits.cpu: 10000m
    limits.memory: 20000Mi