apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: monitoring
spec:
  limits:
  - default:
      memory: 100Mi
      cpu: 0.1
    defaultRequest:
      memory: 50Mi
      cpu: 0.05
    type: Container