apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: "5m"
      smtp_smarthost: "smtp.exmail.qq.com:587"
      smtp_from: "lichenhao@wisetv.com.cn"
      smtp_auth_username: "lichenhao@wisetv.com.cn"
      smtp_auth_password: "bVcyqAh4jnz2hkVg"
      smtp_hello: "qq.com"
      smtp_require_tls: true
    inhibit_rules:
    - equal:
      - "alertname"
      source_match:
        severity: "critical"
      target_match_re:
        severity: "warning|info"
    - equal:
      - "alertname"
      source_match:
        severity: "warning"
      target_match_re:
        severity: "info"
    route:
      group_by:
      - "namespace"
      group_interval: "5m"
      group_wait: "30s"
      receiver: "default"
      repeat_interval: "6h"
      routes:
      - receiver: "network-group"
        group_wait: "10s"
        match:
          network_device: "interface-state"
    receivers:
    - name: "default"
      email_configs:
      - to: "lichenhao@wisetv.com.cn"
        send_resolved: true
    - name: "network-group"
      email_configs:
      - to: "wangpeng@wisetv.com.cn"
        send_resolved: true
      - to: "lichenhao@wisetv.com.cn"
        send_resolved: true
      - to: "zhouhao@wisetv.com.cn"
        send_resolved: true     
type: Opaque
