apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: "5m"
      smtp_smarthost: 'smtp.exmail.qq.com:25'
      smtp_from: 'dev_notify@wisetv.com.cn'
      smtp_auth_username: 'dev_notify@wisetv.com.cn'
      smtp_auth_password: 'Iptv1234'
    inhibit_rules:
    - equal:
      - "alertname"
      source_match:
        severity: "critical"
      target_match_re:
        severity: "warning|info"
    - equal:
      - "alertname"
      source_match:
        severity: "warning"
      target_match_re:
        severity: "info"
    route:
      group_by:
      - "namespace"
      group_interval: "5m"
      group_wait: "30s"
      receiver: "default"
      repeat_interval: "6h"
      routes:
      - receiver: "dev-cms"
        group_wait: "10s"
        match_re:
          job: "external-metrics"
    receivers:
    - name: "default"
      email_configs:
      - to: "lichenhao@wisetv.com.cn"
        send_resolved: true
    - name: "dev-cms"
      email_configs:
      - to: "lichenhao@wisetv.com.cn"
        send_resolved: true      
      - to: "zhangmingqian@wisetv.com.cn"
        send_resolved: true
      - to: 'lijin@wisetv.com.cn'
        send_resolved: true
      - to: 'lizhe2@wisetv.com.cn'
        send_resolved: true
      - to: 'feiwenyu@wisetv.com.cn'
        send_resolved: true      
type: Opaque