- name: 配置主机名
  hostname: 
    name: '{{ inventory_hostname }}'
 
- name: 配置/etc/hosts文件
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: 关闭防火墙
  systemd: 
    name: "{{item}}"
    state: stopped
    enabled: no
  with_items: 
  - iptables
  - firewalld

- name: 禁用SELinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "SELINUX=*"
    line: "SELINUX=disabled"

- name: 关闭SELinux
  shell: "setenforce 0"
  failed_when: false

- name: 关闭swap
  shell: swapoff -a

- name: 禁用swap
  lineinfile: 
    dest: /etc/fstab
    regexp: "([^#].*swap.*)"
    line: '#\1'
    backrefs: yes

- name: 修改sysctl参数
  template:
    src: k8s-sysctl.conf.j2
    dest: /etc/sysctl.d/k8s-sysctl.conf

- name: 读取内核参数
  shell: sysctl -p /etc/sysctl.d/*

- name: 配置ipvs模块
  block: 
  - name: 发送模块配置文件
    copy: 
      src: ip_vs.conf
      dest: /etc/modules-load.d/ip_vs.conf
  - name: 加载模块  
    vars:
      info: "{{ lookup('file', 'ip_vs.conf').splitlines() }}"
    shell: modprobe {{ item }}
    loop: "{{ info }}" 
  when: PROXY.MODE == "ipvs"
  tags:
  - ipvs

- name: 配置k8s源
  template: 
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: 安装k8s工具三件套
  yum:
    name: 
    - kubelet-{{ KUBERNETES_VERSION }}
    - kubeadm-{{ KUBERNETES_VERSION }}
    - kubectl-{{ KUBERNETES_VERSION }}
    state: present

#- name: 配置kubelet
#  shell: echo "KUBELET_EXTRA_ARGS=--cgroup-driver=systemd" > /etc/sysconfig/kubelet

- name: 配置kubelet开机自启
  systemd: 
    daemon_reload: yes
    name: kubelet
    state: stopped
    enabled: yes

- name: 配置其他用户
  include_tasks: user.yml

- name: 配置master
  include_tasks: master.yml
  when: inventory_hostname is search("master")
