{
 "title": "Dell 服务器硬件监控",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "dell 服务器硬件整体状态",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dell_hw_system_status", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "电源功耗",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dell_hw_chassis_power_reading", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "电源电流大小",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "dell_hw_chassis_current_reading",
     "legendFormat": "{{instance}} {{pwrsupply}}"
    }
   ]
  }
 ]
}