{
 "title": "DNS 指标监控",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "DNS 解析请求总数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coredns_dns_request_count_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DNS 相应状态码总数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_dns_response_rcode_count_total)by(rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "DNS 查询速率 (1分钟)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(coredns_dns_request_count_total{zone !=\"dropped\"}[1m]))",
     "legendFormat": "查询速率"
    }
   ]
  },
  {
   "title": "DNS 非NOERROR响应状态码(1分钟)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(coredns_dns_response_rcode_count_total{rcode!=\"NOERROR\"} [1m])",
     "legendFormat": "{{pod}} {{rcode}}"
    }
   ]
  }
 ]
}