{
 "title": "DR 状态",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "dr-1 50080 端口后端状态",
   "type": "stat",
   "description": "ipvs_status 为 node_exporter 的 Textfile Collector 功能手写的时间序列，通过keepalived的realserver配置中 notify_up 和 notify_down 脚本来变更指标值。",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipvs_status{instance=\"dr-1-k8s-cloud\"}",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "dr-2 50080 端口后端状态",
   "type": "stat",
   "description": "ipvs_status 为 node_exporter 的 Textfile Collector 功能手写的时间序列，通过keepalived的realserver配置中 notify_up 和 notify_down 脚本来变更指标值。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipvs_status{instance=\"dr-2-k8s-cloud\"}",
     "legendFormat": "{{remote_address}}"
    }
   ]
  },
  {
   "title": "dr-1 后端活跃连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_active{instance=~\"dr-1-k8s-cloud\",remote_port=\"50080\"}",
     "legendFormat": "{{remote_address}}:{{remote_port}}"
    }
   ]
  },
  {
   "title": "dr-2 后端活跃连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_active{instance=~\"dr-2-k8s-cloud\",remote_port=\"50080\"}",
     "legendFormat": "{{remote_address}}:{{remote_port}}"
    }
   ]
  }
 ]
}