{
 "title": "etcd的简洁dashboard",
 "description": "简洁的etcd监控模板",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "etcd集群数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(etcd_server_has_leader{job=\"etcd\"})"
    }
   ]
  },
  {
   "title": "etcd是否有leader节点",
   "type": "singlestat",
   "description": "has_leader表示该成员是否具有leader 。如果某个成员没有leader ，则完全无法使用。如果群集中的所有成员都没有任何leader ，则整个群集完全不可用。",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "etcd程序占用内存",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\"}   ",
     "legendFormat": "{{instance}} 使用内存"
    }
   ]
  },
  {
   "title": "etcd内部rpc调用失败情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[1m])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "etcd节点容量",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "etcd_debugging_mvcc_db_total_size_in_bytes",
     "legendFormat": "etcd的存储容量"
    }
   ]
  },
  {
   "title": "etcd各个方法调用速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job='etcd'}[1m])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "RPC调用速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "watch和lease",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "etcd节点发送数据速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}}/发送数据速率"
    }
   ]
  },
  {
   "title": "etcd节点接收数据速率",
   "type": "graph",
   "description": "通常leader节点的速率大一些",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total[5m])) by (instance)",
     "legendFormat": "{{instance}} 接收速率"
    }
   ]
  },
  {
   "title": "etcd磁盘平均延时",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum[1m]))",
     "legendFormat": "fsync called by wal 的延迟"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum[1m]))",
     "legendFormat": "commit called by backend 的延迟"
    }
   ]
  },
  {
   "title": "proposals状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{job=\"etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}/已committed的proposals总数"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{job=\"etcd\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}/已applied的proposals总数"
    }
   ]
  },
  {
   "title": "etcd磁盘fsunc的延时",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])) by (instance,le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  }
 ]
}