{
 "title": "手机源站物理资源使用率视图",
 "tags": [ "wisetv" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "海泰WOWZA-CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - irate(node_cpu_seconds_total{instance=\"dev-phone-ht-wowza\",mode=\"idle\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "空港WOWZA-CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - irate(node_cpu_seconds_total{instance=\"dev-phone-ht-wowza\",mode=\"idle\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "海泰HLS-CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - irate(node_cpu_seconds_total{instance=\"dev-phone-ht-hls\",mode=\"idle\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "空港HLS-CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - irate(node_cpu_seconds_total{instance=\"dev-phone-kg-hls\",mode=\"idle\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "海泰WOWZA-MEM使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\n-\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\n-\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\n-\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "空港HLS-MEM使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\n-\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\n-\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\n-\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "海泰HLS-MEM使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\n-\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\n-\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\n-\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "空港WOWZA-MEM使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\n-\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\n-\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\n-\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "海泰WOWZA-DISK使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\",device!=\"rootfs\",device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\",device!=\"rootfs\",device!=\"tmpfs\"}) / node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\",device!=\"rootfs\",device!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "空港WOWZA-DISK使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\",device!=\"rootfs\",device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\",device!=\"rootfs\",device!=\"tmpfs\"}) / node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\",device!=\"rootfs\",device!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "海泰HLS-DISK使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\",device!=\"rootfs\",device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\",device!=\"rootfs\",device!=\"tmpfs\"}) / node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\",device!=\"rootfs\",device!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "空港HLS-DISK使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\",device!=\"rootfs\",device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\",device!=\"rootfs\",device!=\"tmpfs\"}) / node_filesystem_size_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\",device!=\"rootfs\",device!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "海泰WOWZA-内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  (\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"} \r\n- \r\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\r\n- \r\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\r\n  )\r\n/\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\"}\r\n* 100"
    }
   ]
  },
  {
   "title": "海泰HLS-内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  (\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"} \r\n- \r\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\r\n- \r\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\r\n  )\r\n/\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\"}\r\n* 100"
    }
   ]
  },
  {
   "title": "空港WOWZA-内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  (\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"} \r\n- \r\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\r\n- \r\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\r\n  )\r\n/\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\"}\r\n* 100"
    }
   ]
  },
  {
   "title": "空港HLS-内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  (\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"} \r\n- \r\n  node_memory_Cached_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\r\n- \r\n  node_memory_Buffers_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\r\n-\r\n  node_memory_MemFree_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\r\n  )\r\n/\r\n  node_memory_MemTotal_bytes{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\"}\r\n* 100"
    }
   ]
  }
 ]
}