{
 "title": "手机源站流量监控",
 "tags": [ "wisetv" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "海泰防火墙-Internet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"211.137.172.1\",ifAlias=\"TO_INTERNET\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"211.137.172.1\",ifAlias=\"TO_INTERNET\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "空港防火墙-Internet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"43.247.4.129\",ifAlias=\"TO_INTERNET\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"43.247.4.129\",ifAlias=\"TO_INTERNET\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "海泰交换机-TO-WOWZA流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"211.137.172.27\",ifAlias=\"TO_WOWZA\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"211.137.172.27\",ifAlias=\"TO_WOWZA\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "空港交换机-TO-WOWZA流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"43.247.4.159\",ifAlias=\"TO_WISETV-KONGGANG-WOWZA\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"43.247.4.159\",ifAlias=\"TO_WISETV-KONGGANG-WOWZA\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "海泰交换机-TO-HLS流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"211.137.172.27\",ifAlias=\"TO_WISETV-HLS\",ifDescr=\"Bridge-Aggregation1\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"211.137.172.27\",ifAlias=\"TO_WISETV-HLS\",ifDescr=\"Bridge-Aggregation1\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "空港交换机-TO-HLS流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{instance=\"43.247.4.159\",ifAlias=\"TO_WISETV-ARCSOFT-HLS\",ifDescr=\"Bridge-Aggregation24\"}[6m]) * 8",
     "legendFormat": "入流"
    },
    {
     "expr": "irate(ifHCOutOctets{instance=\"43.247.4.159\",ifAlias=\"TO_WISETV-ARCSOFT-HLS\",ifDescr=\"Bridge-Aggregation24\"}[6m]) * 8",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "海泰WOWZA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\", device=\"bond0\"}[$__interval])",
     "legendFormat": "入流"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-ht-wowza\", device=\"bond0\"}[$__interval])",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "空港WOWZA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\", device=\"bond0\"}[$__interval])",
     "legendFormat": "入流"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-kg-wowza\", device=\"bond0\"}[$__interval])",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "海泰HLS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\", device=\"bond0\"}[$__interval])",
     "legendFormat": "入流"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-ht-hls\", device=\"bond0\"}[$__interval])",
     "legendFormat": "出流"
    }
   ]
  },
  {
   "title": "空港HLS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\", device=\"bond0\"}[$__interval])",
     "legendFormat": "入流"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"phone-external-metrics\", instance=\"dev-phone-kg-hls\", device=\"bond0\"}[$__interval])",
     "legendFormat": "出流"
    }
   ]
  }
 ]
}