{
 "title": "集群外部设备指标信息",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info,cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"external-metrics\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - irate(node_cpu_seconds_total{instance=\"$instance\",mode=\"idle\"}[5m]) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"external-metrics\", instance=\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"external-metrics\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"external-metrics\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"external-metrics\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"external-metrics\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"external-metrics\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "  (\n  node_memory_MemTotal_bytes{job=\"external-metrics\", instance=\"$instance\"} \n- \n  node_memory_Cached_bytes{job=\"external-metrics\", instance=\"$instance\"}\n- \n  node_memory_Buffers_bytes{job=\"external-metrics\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"external-metrics\", instance=\"$instance\"}\n  )\n/\n  node_memory_MemTotal_bytes{job=\"external-metrics\", instance=\"$instance\"}\n* 100\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"external-metrics\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+\"}[$__interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"external-metrics\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+\"}[$__interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"external-metrics\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+\"}[$__interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"external-metrics\", instance=\"$instance\",device!=\"rootfs\",device!=\"tmpfs\"} - node_filesystem_avail_bytes{job=\"external-metrics\", instance=\"$instance\",device!=\"rootfs\",device!=\"tmpfs\"}) / node_filesystem_size_bytes{job=\"external-metrics\", instance=\"$instance\",device!=\"rootfs\",device!=\"tmpfs\"}",
     "legendFormat": "{{mountpoint}} 使用率"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"external-metrics\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"external-metrics\", instance=\"$instance\", device!=\"lo\"}[$__interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}