name: Mirroring

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: 
            git@gitee.com:DesistDaydream/Work.git
          ssh_private_key: 
            ${{ secrets.GITEE_PRIVATE_KEY }}
