name: Mirroring

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Mirror to gitee'
        uses: Yikun/hub-mirror-action@master
        with:
          target_repo_url: git@gitee.com:DesistDaydream/Work.git
          ssh_private_key: ${{ secrets.GITEE_PRIVATE_KEY }}
