name: 'GitHub Actions Mirror'

on: [push]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to gitee'
        uses: DesistDaydream/Work@master
        with:
          target_repo_url:
            git@gitee.com:DesistDaydream/Work.git
          ssh_private_key:
            ${{ secrets.GITEE_PRIVATE_KEY }}